---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "30"
year: "2016"
contributor: 
- "Fabio Tullio"
title: "Zur Legitimation Öffentlicher Bibliotheken"
urn: ""
comments: false
sharing: true
footer: true

---
